#! /bin/bash
#
# This entrypoint script will be called everytime a container is started.
#
# Author: Kaj Munhoz Arfvidsson

set -e

# Start SSH
service ssh start

# Get project information
source util/config.sh

source "/opt/ros/$ROS_DISTRO/setup.bash" --

# Micro-ROS Agent environment variables
if [ "$MICROROS_DISABLE_SHM" = "1" ] ; then
    if [ "$ROS_LOCALHOST_ONLY" = "1" ] ; then
        export FASTRTPS_DEFAULT_PROFILES_FILE=/tmp/disable_fastdds_shm_localhost_only.xml
    else
        export FASTRTPS_DEFAULT_PROFILES_FILE=/tmp/disable_fastdds_shm.xml
    fi
fi

# To build anything that has been added by volume...
colcon build --symlink-install

# https://github.com/osrf/docker_images/issues/114
printf "\nsource '$PWD/install/setup.bash'" >> $HOME/.bashrc

# source "/opt/ros/$ROS_DISTRO/setup.bash" --
exec "$@"
