#! /bin/sh
#
# Create a container from an image
#
# The last argument to the script is the image name, this will also be the
# container name after it has been created. The container is will be privileged
# and share the host network.
#
# OBS: This is the development version. The container will not be privileged
# or have access to the host's network.
#
# Author: Kaj Munhoz Arfvidsson


. "$(dirname "$0")/config.sh"


# Setting default arguments
if [ -z "$*" ]
then set -- "$IMAGE_TAG"
fi


[ -n "$DEBUG" ] && fn="echo" || fn="exec"

"$fn" docker create \
    -it \
    -e "TERM=xterm-256color" \
    -v "$SHRVOL_SRC:$SHRVOL_DST" \
    --name "$CONTAINER_NAME" \
    "$*"

