#! /bin/sh

. "$(dirname "$0")/config.sh"

[ $# -gt 1 ] && echo "Invalid arguments: $@" && exit 1
notin "$1" team1 team2 team3 team4 && echo "Invalid arguments: $@" && exit 1

CMD="docker run"
IMAGE="ghcr.io/abconnectio/datastreamer-beta-eap:2e50722-arm64"
ARGS=""

append ARGS \
    -v /dev/video0:/dev/video0 \
    -v /dev/video1:/dev/video1 \
    -v /dev/video2:/dev/video2 \
    -v /dev/video3:/dev/video3 \
    --rm \
    --name fmq \
    --restart unless-stopped \
    --network host \
    --privileged

call $CMD $ARGS $IMAGE -configId=el2425-config -groupId=el2425 -id=$1
