#! /bin/sh
#
# Create and start (run) a container.
#
# The container will be privileged and share the host network.
#
# Author: Kaj Munhoz Arfvidsson

. "$(dirname "$0")/config.sh"

CMD="docker run"
ARGS="$@"

# Default docker arguments
if isempty ARGS; then
    ARGS="--name $CONTAINER_NAME"
fi

# Other docker arguments
append ARGS \
    -it \
    -v "$SHARED_VOLUME" \
    -e "TERM=xterm-256color" \
    --rm \

if istrue DEV; then
    append ARGS \
        -p "8765:8765"
else
    # On macOS, reduce privileges to avoid Docker Desktop issues
    if is_darwin; then
        append ARGS \
            -p "11311:11311" \
            -p "8080:8080" \
            -p "9090:9090"
else
    append ARGS \
        -v "/dev:/dev" \
        --network host \
        --privileged
fi

append ARGS \
    "$IMAGE_TAG"

# Can be debugged with DEBUG=1 env var
call $CMD $ARGS
