#! /bin/sh
#
# Create and start (run) a container.
#
# The container will be privileged and share the host network.
#
# Author: Kaj Munhoz Arfvidsson

. "$(dirname "$0")/config.sh"

# Setting default arguments
if [ -z "$*" ]; then
    set -- --name "$CONTAINER_NAME" "$IMAGE_TAG"
fi

istrue DEBUG && fn="echo" || fn="exec"

"$fn" docker run \
    -it \
    -e "TERM=xterm-256color" \
    -v "/dev:/dev" \
    -v "$SHARED_VOLUME" \
    --rm \
    --network host \
    --privileged \
    "$@"
