#! /bin/sh
#
# Create and start (run) a container.
#
# OBS: This is the development version. The container will
# not be privileged or have access to the host's network.
#
# Author: Kaj Munhoz Arfvidsson

. "$(dirname "$0")/config.sh"

# Setting default arguments
if [ -z "$*" ]
then set -- --name "$CONTAINER_NAME" "$IMAGE_TAG"
fi

istrue DEBUG && fn="echo" || fn="exec"

"$fn" docker run \
    -it \
    -p "8765:8765" \
    -e "TERM=xterm-256color" \
    -v "$SHARED_VOLUME" \
    --rm \
    "$@"

