#! /bin/sh
#
# Start a container
#
# Author: Kaj Munhoz Arfvidsson


. "$(dirname "$0")/config.sh"


if [ -z "$*" ]
then set -- "$CONTAINER_NAME"
fi


[ -n "$DEBUG" ] && fn="echo" || fn="exec"

"$fn" docker start \
    -i \
    "$*"

