amcl:
  ros__parameters:
    alpha1: 0.4
    alpha2: 0.4
    alpha3: 1.6
    alpha4: 0.8
    alpha5: 0.2
    base_frame_id: "base_link"
    introspection_mode: "disabled"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.2
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 50
    max_particles: 800
    min_particles: 100
    odom_frame_id: "odom"
    pf_err: 0.01
    pf_z: 0.99
    recovery_alpha_fast: 0.005
    recovery_alpha_slow: 0.005
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.1
    tf_broadcast: true
    transform_tolerance: 0.01
    update_min_a: 0.01
    update_min_d: 0.01
    z_hit: 0.85
    z_max: 0.05
    z_rand: 0.15
    z_short: 0.05
    scan_topic: scan
    map_topic: map
    set_initial_pose: true
    always_reset_initial_pose: false
    first_map_only: false
    initial_pose:
      x: -7.3699
      y: -15.383940368977647
      z: 0.0
      yaw: 1.0116