<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD

amcl:
  ros__parameters:

    # --- Timing & TF ---
    transform_tolerance: 0.1

    # --- Motion update thresholds (reduce CPU → reduce lag) ---
    update_min_a: 0.01
    update_min_d: 0.01

    # --- Adaptive sampling (KLD) ---
    min_particles: 100
    max_particles: 800
    pf_err: 0.01
    #pf_z: 0.99

    # --- Beam skipping for dynamics/glass --
    do_beamskip: true
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3

    # --- Noise / odom model ---
    alpha1: 0.4                 # rot noise on rot
    alpha2: 0.4                 # rot noise on trans
    alpha3: 1.6                 # trans noise on trans (was 1.6, very high)
    alpha4: 0.8                 # trans noise on rot
    # alpha5: 0.05                # (keep low unless you have strafe)

    # --- Measurement mixture weights ---
    z_hit: 0.85
    z_rand: 0.15                # was 0.15
    z_short: 0.05               # was 0.05
    z_max: 0.05                # was 0.05; often unnecessary with real max range
    sigma_hit: 0.1              # was 0.1; slightly wider for real sensors


    # -- Rest --
    base_frame_id: "base_link"
    global_frame_id: "map"
    odom_frame_id: "odom"
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    resample_interval: 1
    tf_broadcast: true
    map_topic: map
    scan_topic: /scan
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    always_reset_initial_pose: false
    first_map_only: false

    introspection_mode: "disabled"
    lambda_short: 0.2
    laser_likelihood_max_dist: 2.0
    laser_max_range: 20.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 50
    recovery_alpha_fast: 0.005
    recovery_alpha_slow: 0.005
    #save_pose_rate: 0.5
=======
amcl:
  ros__parameters:
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    introspection_mode: "disabled"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan
    map_topic: map
    set_initial_pose: true
    always_reset_initial_pose: false
    first_map_only: false
    initial_pose:
      x: -7.3699
      y: -15.383940368977647
      z: 0.0
      yaw: 1.57
>>>>>>> ecc9d3f (Migration to ROS 2 (#55))
=======
#Overall filter parameters
min_particles: 100 
max_particles: 800
kld_err: 0.01
# kld_z:
update_min_d: 0.01
update_min_a: 0.01
resample_interval: 1
transform_tolerance: 0.01
recovery_alpha_slow: 0.001 #0.005
recovery_alpha_fast: 0.1 #0.005
initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0
initial_cov_xx: 0.5
initial_cov_yy: 0.5
initial_cov_aa: 0.25
# gui_publish_rate
# save_pose_rate
# use_map_topic: true 
# first_map_only
selective_resampling: true
=======
/**:
=======
amcl:
>>>>>>> 2fb2b0b (localization update still have issues)
  ros__parameters:
<<<<<<< HEAD
    #Overall filter parameters
    min_particles: 100 
    max_particles: 800
    kld_err: 0.01
    # kld_z:
    update_min_d: 0.01
    update_min_a: 0.01
    resample_interval: 1
    transform_tolerance: 0.01
    recovery_alpha_slow: 0.001 #0.005
    recovery_alpha_fast: 0.1 #0.005
    # initial_pose_x: 0.0
    # initial_pose_y: 0.0
    # initial_pose_a: 0.0
    initial_cov_xx: 0.5
    initial_cov_yy: 0.5
    initial_cov_aa: 0.25
    # gui_publish_rate
    # save_pose_rate
    # use_map_topic: true 
    # first_map_only
    selective_resampling: true
>>>>>>> b921c25 (Added rmw-zenoh in dockerfile, added svea_example)

    #Laser model parameters
    # laser_min_range
    # laser_max_range
    laser_max_beams: 50 
    laser_z_hit: 0.85   #likelihood_field only uses z_hit and z_rand (should be sum to 1)
    # laser_z_short: 0.05
    # laser_z_max: 0.05
    laser_z_rand: 0.15
    laser_sigma_hit: 0.1
    laser_lambda_short: 0.2
    laser_likelihood_max_dist: 2.0
    laser_model_type: likelihood_field
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

<<<<<<< HEAD
#Odometry model parameters
odom_model_type: diff-corrected
odom_alpha1: 0.4 # Rot from rot
odom_alpha2: 0.4 # Rot from trans
odom_alpha3: 1.6  # Trans from trans
odom_alpha4: 0.8  # Trans from rot
#odom_alpha5: 0.2  Side slipp (not used unless odom_model_type is omni)
# odom_frame_id
# global_frame_id
# tf_broadcast
<<<<<<< HEAD
>>>>>>> a6d4456 (add svea_localization,modifying to ros2 in progress)
=======
=======
    #Odometry model parameters
    odom_model_type: diff-corrected
    odom_alpha1: 0.4 # Rot from rot
    odom_alpha2: 0.4 # Rot from trans
    odom_alpha3: 1.6  # Trans from trans
    odom_alpha4: 0.8  # Trans from rot
    #odom_alpha5: 0.2  Side slipp (not used unless odom_model_type is omni)
    # odom_frame_id
    # global_frame_id
    # tf_broadcast
<<<<<<< HEAD
>>>>>>> e76035e (Added rmw-zenoh in dockerfile, added svea_example)
<<<<<<< HEAD
>>>>>>> b921c25 (Added rmw-zenoh in dockerfile, added svea_example)
=======
=======

=======
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
>>>>>>> 199c690 (localization update still have issues)
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
<<<<<<< HEAD
    scan_topic: /scan
>>>>>>> a0fa786 (udpate lidar.xml and amcl localize.xml to fix AMCL)
<<<<<<< HEAD
>>>>>>> 8177d8a (udpate lidar.xml and amcl localize.xml to fix AMCL)
=======
=======
    lambda_short: 0.1
    laser_frame_id: "laser"
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan

amcl_map_client:
  ros__parameters:
    use_sim_time: True

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: True

map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "sml.yaml"

robot_state_publisher:
  ros__parameters:
    use_sim_time: True
>>>>>>> 199c690 (localization update still have issues)
>>>>>>> 2fb2b0b (localization update still have issues)
