name: Build and Push Docker Image to GHCR

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build the Docker image
      env:
        CONFIG: base
      run: util/build

    - name: Push Docker Image to GHCR
      run: docker push ghcr.io/kth-sml/svea:x86_64

    - name: Log out from GitHub Container Registry
      run: docker logout ghcr.io
